### ISSUE TITLE
Duplication d'un médicament lors de l'annulation d'une modification

### ISSUE THREAD

**Issue by Jean-BaptisteC** [jfoucry/Pilldroid#15]
## Bug
Comment reproduire:
- Modifier un médicament en utilisant le glissement vers la gauche
- Enregistrer la modification
- Cliquer sur Annuler dans la Snackbar -> Le médicament est dupliqué
- Supprimer le premier élément
- Consulter l’élément dupliqué
- Retourner à l'écran précédent -> l'élément disparait

**Comment by jfoucry** [comment]
Hum… Normalement en modification (glissement de la gauche vers la droite, icône de stylo) tu n'a pas la snackbar. Elle n’apparaît qu'en cas de suppression d'un médicament (glissement de la droite vers la gauche, icône de poubelle).

Et en supprimant un médicament, je n'ai pas du tout le comportement que tu décris

**Comment by Jean-BaptisteC** [comment]
Quand tu édites un médicament avec le glissement de la gauche vers la droite, icône de stylo et que tu enregistres.
Tu as une snackbar qui apparait et c'est à ce moment la que tu peux appuyer sur annuler ce qui déclenche la duplication du médicament.
