### ISSUE TITLE
Barre du haut masquée sur Android 12

### ISSUE THREAD

**Issue by Altonss** [jfoucry/Pilldroid#18]
Sur Android 12, la barre du haut (titre) du médicament est en partie masquée

![Screenshot_20220807-124022](https://user-images.githubusercontent.com/66519591/183286961-805ca1a2-f882-4fca-8f65-cfda88896585.png)

**Comment by jfoucry** [comment]
Ce comportement doit être corrigé maintenant. Si ce n'est pas le cas, merci de me dire quel version de pilldroid vous ustilisé, (information sur l'application).

**Comment by Altonss** [comment]
> Ce comportement doit être corrigé maintenant. Si ce n'est pas le cas, merci de me dire quel version de pilldroid vous ustilisé, (information sur l'application).

J'utilise la version v0.302-beta
