### ISSUE TITLE
Bouton enregistrer masque le dernier champ

### ISSUE THREAD

**Issue by Altonss** [jfoucry/Pilldroid#19]
Lorsqu'on essaye d'éditer les champs d'un médicament, le bouton "enregistrer" masque le dernier champ seuil critique (parce que le clavier est ouvert).
Ce n'est vraiment pas un gros souci, mais sans doute que ce n'est pas un souci très difficile à régler et qui pourrait faciliter l'accesibilité de l'application :) Je vais essayer de réfléchir à une solution si j'ai du temps ^^
![Screenshot_20220807-124244](https://user-images.githubusercontent.com/66519591/183287090-13ab3701-b639-47b3-a220-c00802fc3338.png)

**Comment by Jean-BaptisteC** [comment]
Des news sur le sujet ?
Une solution serait de revoir comment l'agencement de l'item champ

**Comment by jfoucry** [comment]
Résolut par @Jean-BaptisteC Merci à toi

**Comment by Jean-BaptisteC** [comment]
Le problème n'est pas corrigé, j'ai prévu de faire une PR plutôt utiliser un bouton flottant centré
https://m3.material.io/components/extended-fab/overview
