### ISSUE TITLE
Create a CustomScanContrat from zxing:scanContract

### ISSUE THREAD

**Issue by jfoucry** [jfoucry/Pilldroid#5]
In order to use the `CustomScannerActivity`, need to create a custon ScanContract fron the Zxing scanContrat. For now unsuccessfully, 

There is 3 buttons in my `CustomScannerActivty`:
- cancel
- torch (which work)
- keyboard

I need to catch the `resultCode` from those button.

Branch Fix_zxing_calling

**Comment by Altonss** [comment]
Hello @jfoucry,
Do you now Catima https://github.com/CatimaLoyalty/Android ? Maybe the implementation of this app could help you! I am not an android expert at all, but maybe you can look at this https://github.com/CatimaLoyalty/Android/blob/master/app/src/main/java/protect/card_locker/ScanActivity.java

**Comment by jfoucry** [comment]
Oh! I just had a look to the app and it look like something near what I am looking for. I will look at the sources this evening.
Thanks for the suggestion.

**Comment by jfoucry** [comment]
half solved.
Successfully create a contract for the scan but failed to create a contract for my own acrtivity `DrugDetais`. For those call I keep the old way and add `@SuppressWarning("deprecation")`  just before using it.
