### ISSUE TITLE
Improve translate in French

### ISSUE THREAD

**Issue by Jean-BaptisteC** [jfoucry/Pilldroid#8]
That's great project ✨
I have check translation in French, i think we can improve this (fix typo, improve sentences, ...)
I want improve:

- [Metadata files](https://github.com/jfoucry/Pilldroid/tree/develop/fastlane/metadata/android)
- [Values](https://github.com/jfoucry/Pilldroid/blob/develop/app/src/main/res/values-fr-rFR/strings.xml)

**Comment by jfoucry** [comment]
Feel free to make a PR. I will be happy!
